BookStore/ViewModels/BookViewModel.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookStore.ViewModels
{
    public class BookViewModel
    {
        public BookModels Book { get; set; }
        public IEnumerable<BookGenreModels> Genres { get; set; }
        public IEnumerable<MovieModels> RelatedMovie { get; set; }
    }
}

BookStore/Controllers/Api/BooksController.cs
using AutoMapper;
using BookStore.Dtos;
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace BookStore.Controllers.Api
{
    public class BooksController : ApiController
    {
        private ApplicationDbContext applicationDbContext;

        public BooksController()
        {
            applicationDbContext = new ApplicationDbContext();
        }

        //GET api/books/
        public IEnumerable<BookDto> GetBooks()
        {
            return applicationDbContext.Books.ToList().Select(Mapper.Map<BookModels, BookDto>);             
        }

        //GET api/books/1
        public IHttpActionResult GetBook(int id)
        {
            var book = applicationDbContext.Books.SingleOrDefault(b => b.Id == id);

            if (book == null)
                return NotFound();

            return Ok(Mapper.Map<BookModels, BookDto>(book));
        }

        //POST api/books
        [HttpPost]
        public IHttpActionResult CreateBook(BookDto bookDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var book = Mapper.Map<BookDto, BookModels>(bookDto);
                        
            book.ImageData = null;
            book.ImageMimeType = null;

            applicationDbContext.Books.Add(book);
            applicationDbContext.SaveChanges();

            bookDto.Id = book.Id;
            
            return Created(new Uri(Request.RequestUri + "/" + book.Id), bookDto);
        }

        //PUT api/books/1
        [HttpPut]
        public IHttpActionResult UpdateBook(int id, BookDto bookDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var bookInDb = applicationDbContext.Books.SingleOrDefault(b => b.Id == id);

            if (bookInDb == null)
                return NotFound();

            Mapper.Map(bookDto, bookInDb);

            applicationDbContext.SaveChanges();

            return Ok();
        }

        //DELETE api/books/1
        [HttpDelete]
        public IHttpActionResult DeleteBook(int id)
        {
            var bookInDb = applicationDbContext.Books.SingleOrDefault(b => b.Id == id);

            if (bookInDb == null)
                return NotFound();

            applicationDbContext.Books.Remove(bookInDb);
            applicationDbContext.SaveChanges();

            return Ok();
        }
    }
}

BookStore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using BookStore.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace BookStore.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext dbContext = new ApplicationDbContext();
        private IList<string> roles = new List<string>();
        private ApplicationUserManager userManager = null;
        private ApplicationUser user = null;

        // GET: Books
        public ActionResult Index()
        {            
            var books = dbContext.Books.Include(book => book.MovieModels).ToList();

            userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            user = userManager.FindByEmail(User.Identity.Name);
            if (user != null)
                roles = userManager.GetRoles(user.Id);
            var admin = roles.Contains("admin");
            ViewBag.Admin = admin;

            return View(books);
        }

        public FileContentResult GetImage(int bookId)
        {
            BookModels book = dbContext.Books
                .FirstOrDefault(g => g.Id == bookId);

            if (book != null)
            {
                return File(book.ImageData, book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookModels bookModels = dbContext.Books.Find(id);
            if (bookModels == null)
            {
                return HttpNotFound();
            }

            userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            user = userManager.FindByEmail(User.Identity.Name);
            if (user != null)
                roles = userManager.GetRoles(user.Id);
            var admin = roles.Contains("admin");
            ViewBag.Admin = admin;

            return View(bookModels);
        }

        // GET: Books/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            var genres = dbContext.BookGenres.ToList();
            var movies = dbContext.Movies.ToList();
            var viewModel = new BookViewModel()
            {
                Book = new BookModels(),
                Genres = genres,
                RelatedMovie = movies
            };
            return View(viewModel);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        //[Bind(Include = "Id,Name,Author,ReleaseYear,Description,Price")]
        public ActionResult Create(BookViewModel bookModels, HttpPostedFileBase uploadImage) /*, HttpPostedFileBase uploadImage*/
        {
            //&& uploadImage != null
            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                    // установка массива байтов
                    bookModels.Book.ImageMimeType = uploadImage.ContentType;
                    bookModels.Book.ImageData = imageData;
                }

                if (bookModels.Book.MovieModels.Id == null)
                {
                    bookModels.Book.MovieModels.Id = 0;
                }

                bookModels.Book.BookGenreModels = dbContext.BookGenres.Find(bookModels.Book.BookGenreModels.Id);
                bookModels.Book.MovieModels = dbContext.Movies.Find(bookModels.Book.MovieModels.Id);
                dbContext.Books.Add(bookModels.Book);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bookModels);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookModels bookModels = dbContext.Books.Find(id);
            if (bookModels == null)
            {
                return HttpNotFound();
            }

            userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            user = userManager.FindByEmail(User.Identity.Name);
            if (user != null)
                roles = userManager.GetRoles(user.Id);

            ViewBag.Roles = roles;

            return View(bookModels);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,Name,Author,ReleaseYear,Description,Price")] BookModels bookModels, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid && uploadImage != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                // установка массива байтов
                bookModels.ImageMimeType = uploadImage.ContentType;
                bookModels.ImageData = imageData;
                

                dbContext.Entry(bookModels).State = EntityState.Modified;
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookModels);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookModels bookModels = dbContext.Books.Find(id);
            if (bookModels == null)
            {
                return HttpNotFound();
            }
            return View(bookModels);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            BookModels bookModels = dbContext.Books.Find(id);
            dbContext.Books.Remove(bookModels);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dbContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookStore/Controllers/CartController.cs
using BookStore.Models;
using BookStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cart
        public ViewResult Index(CartModels cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(CartModels cart, int id, string returnUrl)
        {
            BookModels book = db.Books
                .FirstOrDefault(b => b.Id == id);

            if (book != null)
            {
                cart.AddItem(book, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(CartModels cart, int id, string returnUrl)
        {
            BookModels book = db.Books
                .FirstOrDefault(g => g.Id == id);

            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(CartModels cart)
        {
            return PartialView(cart);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookStore/Views/Books/Create.cshtml
@model BookStore.ViewModels.BookViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>BookModels</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Book.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Book.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Book.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.Author, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Book.Author, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Book.Author, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.BookGenreModels, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Book.BookGenreModels.Id,
                                  new SelectList(Model.Genres, "Id", "Name"),
                                  "Genre of book",
                                  new
                                  {
                                      @class = "form-control",
                                      OnMouseDown = "this.size=5;",
                                      OnFocusOut = "this.size=1;",
                                      OnDblClick = "this.size=1;"
                                  })
            @Html.ValidationMessageFor(model => model.Book.BookGenreModels.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.MovieModels, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Book.MovieModels.Id,
                                  new SelectList(Model.RelatedMovie, "Id", "Name"),
                                  "No related movie",
                                  new
                                  {
                                      @class = "form-control",
                                      OnMouseDown = "this.size=5;",
                                      OnFocusOut = "this.size=1;",
                                      OnDblClick = "this.size=1;"
                                  })
            @Html.ValidationMessageFor(model => model.Book.MovieModels, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Book.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Book.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Book.ReleaseYear, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Book.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Book.Description, new { htmlAttributes = new { @class = "form-control", rows = "3" } })
            @Html.ValidationMessageFor(model => model.Book.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label for="exampleInputFile" class="bmd-label-floating col-md-2">Image</label>
        <div class="col-md-10">
            <input type="file" class="form-control-file" id="exampleInputFile" name="uploadImage">
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Book.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Book.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Book.Price, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookStore/Views/Books/Delete.cshtml
@model BookStore.Models.BookModels

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookStore/Views/Books/Details.cshtml
@model BookStore.Models.BookModels

@{
    ViewBag.Title = "Book details: " + Model.Name;
}

<div class="container">
    <div class="container card pr-3" style="width: 38rem;">
        <div class="row align-self-center">
            <div class="col-6 pr-0 pl-0">
                @if (Model.ImageData == null)
                {
                    <img class="card-img-top" style='max-width:310px; max-height:460px;' src="~/Content/img/No_Photo_Available.jpg" alt="Card image cap">
                }
                else
                {
                    @Html.Raw("<img style='max-width:310px; max-height:460px;' src=\"data:image/jpeg;base64,"
                    + Convert.ToBase64String(Model.ImageData) + "\" />")
                }
                @*@Html.Raw("<img style='max-width:300px; max-height:470px;' src=\"data:image/jpeg;base64,"*@
                                @*+ Convert.ToBase64String(Model.ImageData) + "\" />")*@
                @*<img class="card-img-top" src="~/Content/HPandPS.jpg" alt="Card image cap">*@
            </div>
            <div class="col-6 pl-3">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold text-center">@Model.Name</h5>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <a class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.Author):
                        </a>
                        @Html.DisplayFor(model => model.Author)
                    </li>
                    <li class="list-group-item">
                        <a class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.ReleaseYear):
                        </a>
                        @Html.DisplayFor(model => model.ReleaseYear)
                    </li>
                    <li class="list-group-item">
                        <a class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.Price):
                        </a>
                        @Html.DisplayFor(model => model.Price)
                    </li>
                    <li class="list-group-item">
                        <a class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.Description):
                        </a>
                        @Html.DisplayFor(model => model.Description)
                    </li>
                </ul>
                <div class="container">
                    <div class="row justify-content-center align-items-center pt-4">
                        @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = Model.Id, returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default p-3" })
                        @Html.ActionLink("Back to list", "Index", "Book", new { @class = "btn btn-default p-3" })
                        @if (ViewBag.Admin)
                        {
                            @Html.ActionLink("Edit book", "Edit", new { id = Model.Id }, new { @class = "btn btn-default p-3" })
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BookStore/Views/Books/Edit.cshtml
@model BookStore.Models.BookModels

@{
    ViewBag.Title = "Edit book";
}

<div class="container col-10">
    <!-- Default form login -->
    @using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { enctype = "multipart/form-data", @class = "w-75" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit book</h4>
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="exampleInputFile" class="bmd-label-floating col-md-2">Image</label>
                <div class="col-md-10">
                    <input type="file" class="form-control-file" id="exampleInputFile" name="uploadImage">
                </div>
            </div>

            <div class="form-group">
                <div row justify-content-center align-items-center pt-4>
                    <input type="submit" value="Save changes" class="btn btn-default p-3" />

                    @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-default p-3" })
                </div>
            </div>

        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookStore/Views/Books/Index.cshtml
@model IEnumerable<BookStore.Models.BookModels>

@{
    ViewBag.Title = "Books for sale";
}

<p class="text-center">    
    @if (ViewBag.Admin)
    {
        @Html.ActionLink("Add new book", "Create", null, new { @class = "btn btn-default" })
    }
</p>

<div class="container flex-center">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-5 ">
                <div class="container-fluid">
                    <div class="card-deck">
                        <div class="card" style="width:18rem">
                            @if (item.ImageData == null)
                            {
                                <img class="card-img-top" style='max-width:310px; max-height:450px;' src="~/Content/img/No_Photo_Available.jpg" alt="Card image cap">
                            }
                            else
                            {
                                @Html.Raw("<img style='max-width:310px; max-height:450px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(item.ImageData) + "\" />")
                            }
                            <div class="card-body pb-0" style="height:121px">
                                <h5 class="card-title font-weight-bold text-center">@Html.ActionLink(@item.Name, "Details", new { id = item.Id }, new { @class = "nav-link" })</h5>

                            </div>
                            <hr />
                            <div class="card-body text-center pt-0">
                                @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = item.Id, returnUrl = Request.Url.PathAndQuery }, new { @class = "card-link" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>